# MySQL驱动类（MySQL8.0及以上用这个）
driver=com.mysql.cj.jdbc.Driver
# 数据库连接地址，替换成你自己的数据库IP和端口
url=jdbc:mysql://localhost:3306/chat_with_you?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
# 数据库用户名
username=root
# 数据库密码，替换成你自己的MySQL密码
password=123456